repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix-only ]
      # Run the formatter.
      #- id: ruff-format

ci:
    autofix_commit_msg: "[pre-commit.ci] auto fixes for ruff linting violations"
