default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      # Run the linter, applying any available fixes
      - id: ruff-check
        stages: [ pre-commit, pre-push ]
        args: [ --fix-only ]
