name: qt5_win
channels:
  - conda-forge
dependencies:
 - alabaster
 - colorama
 - ipykernel
 - ipython
 - jupyter
 - nbformat
 - pyopencl=2021.1.6
 - scipy=1.5.3
 - hdf5=1.10.4
 - h5py=2.9.0
 - lxml=4.6.3
 - twisted=21.2.0
 - sphinx=1.8.5
 - pytest=4.2.0
 - cython=0.29.22
 - sip
 - numba=0.39
 - setuptools=49.6.0
 - numpy=1.19.5
 - qtconsole=5.0.3
 - pyzmq=19.0.1   # issues with qtconsole when upgrading!
 - mkl=2021.2.0
 - pip:
   - ordered-set==4.0.2
   - matplotlib==3.1.0
   - bumps==0.7.11
   - pyinstaller==3.3.1
   - periodictable==1.5.0
   - xhtml2pdf==0.2.3
   - ../../../PyQt5_commercial-5.12.2-5.12.3-cp35.cp36.cp37.cp38-none-win_amd64.whl
   - qt5reactor==0.5
   - tinycc==1.1
   - pillow==8.1.2
