name: qt5_osx
channels:
  - conda-forge
  - schrodinger
  - defaults
dependencies:
 - altgraph
 - appdirs
 - attrs
 - automat
 - babel
 - backports.functools_lru_cache
 - ca-certificates
 - certifi
 - clangdev
 - colorama
 - constantly
 - coverage
 - cython
 - h5py
 - hypothesis
 - lxml
 - macholib
 - matplotlib=2.2.2
 - mako
 - numpy=1.15.1=py36_blas_openblashd3ea46f_1
 - openssl
 - packaging
 - pip
 - pycrypto
 - pyinstaller
 - pyqt
 - pytools
 - qt=5.6.2
 - qtconsole
 - sphinx
 - sphinxcontrib-websupport
 - tbb
 - typing
 - service_identity
 - twisted
 - zope
 - scipy
 - hdf5
 - ipykernel=4.9.0
 - jupyter
 - jupyter_client=5.2.4
 - pytest
 - testpath
 - numpy
 - pyopencl
 - sphinx=1.7.4
 - clang_osx-64
 - libgfortran=3.0.1=2000
 - pip:
   - pytools
   - periodictable
   - bumps
   - xhtml2pdf
   - qt5reactor

