# Form implementation generated from reading ui file 'DataViewerUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DataViewer(object):
    def setupUi(self, DataViewer):
        DataViewer.setObjectName("DataViewer")
        DataViewer.resize(700, 680)
        DataViewer.setMinimumSize(QtCore.QSize(700, 680))
        DataViewer.setMaximumSize(QtCore.QSize(700, 680))
        self.cmdClose = QtWidgets.QPushButton(parent=DataViewer)
        self.cmdClose.setGeometry(QtCore.QRect(620, 650, 75, 24))
        self.cmdClose.setObjectName("cmdClose")
        self.comboBoxModifier = QtWidgets.QComboBox(parent=DataViewer)
        self.comboBoxModifier.setGeometry(QtCore.QRect(10, 650, 241, 22))
        self.comboBoxModifier.setObjectName("comboBoxModifier")
        self.cmdAddModifier = QtWidgets.QPushButton(parent=DataViewer)
        self.cmdAddModifier.setGeometry(QtCore.QRect(260, 650, 91, 24))
        self.cmdAddModifier.setObjectName("cmdAddModifier")

        self.retranslateUi(DataViewer)
        QtCore.QMetaObject.connectSlotsByName(DataViewer)

    def retranslateUi(self, DataViewer):
        _translate = QtCore.QCoreApplication.translate
        DataViewer.setWindowTitle(_translate("DataViewer", "Data Viewer"))
        self.cmdClose.setText(_translate("DataViewer", "Close"))
        self.cmdAddModifier.setText(_translate("DataViewer", "Add Modifier"))
