# Form implementation generated from reading ui file 'FitPageUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_fitPageWidget(object):
    def setupUi(self, fitPageWidget):
        fitPageWidget.setObjectName("fitPageWidget")
        fitPageWidget.resize(400, 300)
        self.doubleSpinBox_scale = QtWidgets.QDoubleSpinBox(parent=fitPageWidget)
        self.doubleSpinBox_scale.setGeometry(QtCore.QRect(80, 100, 62, 22))
        self.doubleSpinBox_scale.setMinimum(0.0)
        self.doubleSpinBox_scale.setMaximum(1000.0)
        self.doubleSpinBox_scale.setProperty("value", 1.0)
        self.doubleSpinBox_scale.setObjectName("doubleSpinBox_scale")
        self.doubleSpinBox_radius = QtWidgets.QDoubleSpinBox(parent=fitPageWidget)
        self.doubleSpinBox_radius.setGeometry(QtCore.QRect(80, 130, 62, 22))
        self.doubleSpinBox_radius.setMinimum(0.0)
        self.doubleSpinBox_radius.setMaximum(1000.0)
        self.doubleSpinBox_radius.setProperty("value", 1.0)
        self.doubleSpinBox_radius.setObjectName("doubleSpinBox_radius")
        self.label_a = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_a.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.label_a.setObjectName("label_a")
        self.label_b = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_b.setGeometry(QtCore.QRect(20, 130, 51, 16))
        self.label_b.setObjectName("label_b")
        self.label_equation = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_equation.setGeometry(QtCore.QRect(20, 70, 211, 16))
        self.label_equation.setObjectName("label_equation")
        self.comboBoxFormFactor = QtWidgets.QComboBox(parent=fitPageWidget)
        self.comboBoxFormFactor.setGeometry(QtCore.QRect(20, 20, 131, 22))
        self.comboBoxFormFactor.setObjectName("comboBoxFormFactor")
        self.doubleSpinBox_height = QtWidgets.QDoubleSpinBox(parent=fitPageWidget)
        self.doubleSpinBox_height.setGeometry(QtCore.QRect(80, 160, 62, 22))
        self.doubleSpinBox_height.setMinimum(0.0)
        self.doubleSpinBox_height.setMaximum(1000.0)
        self.doubleSpinBox_height.setProperty("value", 1.0)
        self.doubleSpinBox_height.setObjectName("doubleSpinBox_height")
        self.label_c = QtWidgets.QLabel(parent=fitPageWidget)
        self.label_c.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.label_c.setObjectName("label_c")
        self.checkBoxCreateFit = QtWidgets.QCheckBox(parent=fitPageWidget)
        self.checkBoxCreateFit.setGeometry(QtCore.QRect(210, 20, 181, 20))
        self.checkBoxCreateFit.setObjectName("checkBoxCreateFit")
        self.checkBox2dData = QtWidgets.QCheckBox(parent=fitPageWidget)
        self.checkBox2dData.setGeometry(QtCore.QRect(210, 40, 171, 20))
        self.checkBox2dData.setObjectName("checkBox2dData")

        self.retranslateUi(fitPageWidget)
        QtCore.QMetaObject.connectSlotsByName(fitPageWidget)

    def retranslateUi(self, fitPageWidget):
        _translate = QtCore.QCoreApplication.translate
        fitPageWidget.setWindowTitle(_translate("fitPageWidget", "Form"))
        self.label_a.setText(_translate("fitPageWidget", "Scale"))
        self.label_b.setText(_translate("fitPageWidget", "Radius"))
        self.label_equation.setText(_translate("fitPageWidget", "Parameters for scattering function P(q)"))
        self.label_c.setText(_translate("fitPageWidget", "Height"))
        self.checkBoxCreateFit.setText(_translate("fitPageWidget", "Create Fit for generated Data"))
        self.checkBox2dData.setText(_translate("fitPageWidget", "Generate 2D data"))
