# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 560)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cmdCalculate.setGeometry(QtCore.QRect(500, 490, 91, 24))
        self.cmdCalculate.setObjectName("cmdCalculate")
        self.fittingTabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.fittingTabs.setGeometry(QtCore.QRect(10, 10, 681, 471))
        self.fittingTabs.setObjectName("fittingTabs")
        self.cmdShowDataViewer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cmdShowDataViewer.setGeometry(QtCore.QRect(10, 490, 111, 24))
        self.cmdShowDataViewer.setObjectName("cmdShowDataViewer")
        self.cmdPlot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cmdPlot.setGeometry(QtCore.QRect(600, 490, 91, 24))
        self.cmdPlot.setObjectName("cmdPlot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 22))
        self.menubar.setObjectName("menubar")
        self.menuFitPages = QtWidgets.QMenu(parent=self.menubar)
        self.menuFitPages.setObjectName("menuFitPages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewFitPage = QtGui.QAction(parent=MainWindow)
        self.actionNewFitPage.setObjectName("actionNewFitPage")
        self.menuFitPages.addAction(self.actionNewFitPage)
        self.menubar.addAction(self.menuFitPages.menuAction())

        self.retranslateUi(MainWindow)
        self.fittingTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmdCalculate.setText(_translate("MainWindow", "Calculate"))
        self.cmdShowDataViewer.setText(_translate("MainWindow", "Show Data Viewer"))
        self.cmdPlot.setText(_translate("MainWindow", "Plot"))
        self.menuFitPages.setTitle(_translate("MainWindow", "Fit Pages"))
        self.actionNewFitPage.setText(_translate("MainWindow", "New Fit Page"))
