"""
    Application appearance custom configuration
"""
DATAPANEL_WIDTH = 260
CLEANUP_PLOT = False
FIXED_PANEL = True
PLOPANEL_WIDTH = 420
DATALOADER_SHOW = True
GUIFRAME_HEIGHT = 840
GUIFRAME_WIDTH = 1180
DEFAULT_OPEN_FOLDER = None
WELCOME_PANEL_SHOW = False
TOOLBAR_SHOW = True
DEFAULT_PERSPECTIVE = "Fitting"
