#Application appearance custom configuration
DATAPANEL_WIDTH = 235
FIXED_PANEL = True
PLOPANEL_WIDTH = 415
DATALOADER_SHOW = True
GUIFRAME_HEIGHT = 840
GUIFRAME_WIDTH = 1150
WELCOME_PANEL_SHOW = False
TOOLBAR_SHOW = True
DEFAULT_PERSPECTIVE = 'Fitting'
