"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup
import periodictable.xsf
import DataLoader.readers 
from distutils.sysconfig import get_python_lib
import os

DATA_FILES = []
RESOURCES_FILES = []

#Periodictable data file
DATA_FILES = periodictable.data_files()

#CANSAxml reader data files
RESOURCES_FILES.append(os.path.join(DataLoader.readers.get_data_path(),'defaults.xml'))

APP = ['sansview.py']
DATA_FILES = ['images','test','plugins','doc']
OPTIONS = {'argv_emulation': True,
           'packages': ['lxml','periodictable'],
           'iconfile': 'images/ball.icns',
           'frameworks':['/usr/local/lib/libxml2.2.dylib'], ##This dir path could be /usr/lib/yourlibxmlfile depending on the system.
           'resources': RESOURCES_FILES
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    include_package_data= True,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
