


all:
	gcc test.c ../src/disp_cylinder.c ../src/c_disperser.c \
	../../sans/models/c_extensions/cylinder.c \
	../../libigor/libCylinder.c \
	../src/weighted_cylinder.c \
	-I ../../sans/models/c_extensions -I ../../libigor -I ../include \
	-o test