package:
  name: bumps
  version: !!str 0.7.5.4

source:
  fn: bumps-0.7.5.4.tar.gz
  url: https://pypi.python.org/packages/source/b/bumps/bumps-0.7.5.4.tar.gz
  md5: a47c035fbb18afa5ca53067506a5ff1c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bumps = bumps:main
    #
    # Would create an entry point called bumps that calls bumps.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - bumps
    - bumps.dream
    - bumps.gui
    - bumps.gui.resources
    - bumps.mystic
    - bumps.mystic.examples
    - bumps.mystic.optimizer

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.reflectometry.org/danse/software.html
  license: UNKNOWN
  summary: 'Data fitting with bayesian uncertainty analysis'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
