# Generated by Django 4.2.2 on 2023-07-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, help_text='This is a file', null=True, upload_to=''),
        ),
    ]
