# Generated by Django 4.2.2 on 2023-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_data_file_name_alter_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='File name', max_length=200, null=True),
        ),
    ]
