__major_version__ = "4"
__minor_version__ = "2"
__version__ = __major_version__ + "." + __minor_version__ + ".1"
__DOI__ = "Zenodo, 10.5281/zenodo.1412041"
__release_date__ = "2019"
__build__ = "GIT_COMMIT"
