"""
Application appearance custom configuration
"""
DATAPANEL_WIDTH = -1
CLEANUP_PLOT = False
FIXED_PANEL = True
PLOPANEL_WIDTH = -1
DATALOADER_SHOW = True
GUIFRAME_HEIGHT = -1
GUIFRAME_WIDTH = -1
CONTROL_WIDTH = -1
CONTROL_HEIGHT = -1
DEFAULT_OPEN_FOLDER = None
WELCOME_PANEL_SHOW = False
TOOLBAR_SHOW = True
DEFAULT_PERSPECTIVE = "Fitting"
SAS_OPENCL = "None"
MARKETPLACE_URL = "http://marketplace.sasview.org/"

# Logging options
FILTER_DEBUG_LOGS = True

# Preferences Panel Options
PLOTTER_I_ABS_UNIT = "cm^{-1}"
PLOTTER_I_ABS_SQUARE_UNIT = "cm^{-2}"
PLOTTER_I_SESANS = "A^{-2} cm^{-1}"
PLOTTER_I_ARB = "a.u."
PLOTTER_Q_LENGTH = "A"
PLOTTER_Q_INV_LENGTH = "A^{-1}"
LOADER_I_UNIT_ON_LOAD = "cm^{-1}"
LOADER_Q_UNIT_ON_LOAD = "A^{-1}"
