# Generated by Django 4.2.2 on 2023-07-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyze", "0002_alter_analysisbase_model_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisbase",
            name="model_id",
        ),
        migrations.AddField(
            model_name="analysismodelbase",
            name="base_id",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="analyze.analysisbase",
            ),
        ),
    ]
