# Generated by Django 4.2.2 on 2023-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0005_alter_analysisbase_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='unit',
            field=models.CharField(blank=True, help_text='string for what unit the parameter is', max_length=100, null=True),
        ),
    ]
