# Generated by Django 4.2.2 on 2023-08-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0006_alter_analysisparameterbase_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisbase',
            name='name',
            field=models.CharField(blank=True, help_text='name used for multiple fits', max_length=300),
        ),
        migrations.AddField(
            model_name='analysisparameterbase',
            name='analyze',
            field=models.BooleanField(default=False, help_text='Should this parameter be analyzed?'),
        ),
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='data_type',
            field=models.CharField(blank=True, default=None, help_text='parameter type (int/double)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='value',
            field=models.FloatField(blank=True, default=None, help_text='the value of the parameter', null=True),
        ),
    ]
