#Application appearance custom configuration
DATAPANEL_WIDTH = 235
FIXED_PANEL = True
PLOPANEL_WIDTH = 415
DATALOADER_SHOW = False
GUIFRAME_HEIGHT = 100
GUIFRAME_WIDTH = 400
CLEANUP_PLOT = False
WELCOME_PANEL_SHOW = False
TOOLBAR_SHOW = False
DEFAULT_PERSPECTIVE = "Calculator"
