# Generated by Django 4.2.2 on 2023-07-25 19:56

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_data_file_path_alter_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_name',
            field=models.CharField(default="", help_text='File name', max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(default=None, help_text='This is a file', storage=data.models.FileSystemStorage(), upload_to='uploaded_files'),
        ),
    ]
