python -m UnitTesting.TestUtilsTest
python -m UnitTesting.WelcomePanelTest
python -m UnitTesting.DataExplorerTest
python -m UnitTesting.GuiManagerTest
python -m UnitTesting.MainWindowTest
python -m UnitTesting.GuiUtilsTest
python -m UnitTesting.AboutBoxTest
python -m UnitTesting.DroppableDataLoadWidgetTest
python -m UnitTesting.PlotHelperTest
python -m UnitTesting.SasviewLoggerTest
python -m UnitTesting.PlotterTest
python -m UnitTesting.Plotter2DTest
python -m UnitTesting.ScalePropertiesTest
python -m UnitTesting.KiessigCalculatorTest
python -m UnitTesting.DensityCalculatorTest
