python -m UnitTesting.TestUtilsTest
python -m UnitTesting.WelcomePanelTest
python -m UnitTesting.DataExplorerTest
python -m UnitTesting.GuiManagerTest
python -m UnitTesting.MainWindowTest
python -m UnitTesting.GuiUtilsTest
python -m UnitTesting.AboutBoxTest
python -m UnitTesting.DroppableDataLoadWidgetTest
python -m UnitTesting.PlotHelperTest
python -m UnitTesting.SasviewLoggerTest
python -m UnitTesting.PlotterBaseTest
python -m UnitTesting.PlotterTest
python -m UnitTesting.Plotter2DTest
python -m UnitTesting.ScalePropertiesTest
python -m UnitTesting.KiessigCalculatorTest
python -m UnitTesting.DensityCalculatorTest
python -m UnitTesting.WindowTitleTest
python -m UnitTesting.AddTextTest
python -m UnitTesting.SetGraphRangeTest
python -m UnitTesting.LinearFitTest
python -m UnitTesting.PlotPropertiesTest
python -m UnitTesting.PlotUtilitiesTest
python -m UnitTesting.ColorMapTest
python -m UnitTesting.BoxSumTest
python -m UnitTesting.SlicerModelTest
