# Generated by Django 4.2.2 on 2023-08-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('analysisbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyze.analysisbase')),
                ('results', models.CharField(blank=True, help_text='the string result', max_length=1000000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Complete')], default=1)),
                ('q_minimum', models.FloatField(blank=True, default=0.0005, help_text='Minimum Q value for the fit', null=True)),
                ('q_maximum', models.FloatField(blank=True, default=0.5, help_text='Maximum Q value for the fit', null=True)),
                ('polydispersity', models.BooleanField(default=False, help_text='Is polydispersity being checked in this model')),
                ('magnetism', models.BooleanField(default=False, help_text='Is magnetism being checked in this model?')),
                ('model', models.CharField(help_text='model string', max_length=256)),
                ('optimizer', models.CharField(blank=True, help_text='optimizer string', max_length=50)),
            ],
            bases=('analyze.analysisbase',),
        ),
        migrations.CreateModel(
            name='FitParameter',
            fields=[
                ('analysisparameterbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analyze.analysisparameterbase')),
                ('polydisperse', models.BooleanField(default=False, help_text='Is this a polydisperse parameter?')),
                ('magnetic', models.BooleanField(default=False, help_text='is this a magnetic parameter?')),
            ],
            bases=('analyze.analysisparameterbase',),
        ),
    ]
