# Generated by Django 4.2.2 on 2023-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0004_fit_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='status',
            field=models.IntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Complete')], default=1),
        ),
    ]
