#!/usr/bin/env python
""" Provide functionality for a C extension model

	WARNING: THIS FILE WAS GENERATED BY WRAPPERGENERATOR.PY
 	         DO NOT MODIFY THIS FILE, MODIFY ..\prototypes\src\simcylinder_fast.h
 	         AND RE-RUN THE GENERATOR SCRIPT

    @author: Mathieu Doucet / UTK
    @contact: mathieu.doucet@nist.gov
"""

from sans.models.BaseComponent import BaseComponent
from sans_extension.prototypes.c_models import CSimCylinderF
import copy    
    
class SimCylinderF(CSimCylinderF, BaseComponent):
    """ Class that evaluates a SimCylinderF model. 
    	This file was auto-generated from ..\prototypes\src\simcylinder_fast.h.
    	Refer to that file and the structure it contains
    	for details of the model.
    	List of default parameters:
         scale           = 1.0 
         radius          = 20.0 
         length          = 400.0 
         theta           = 0.0 
         phi             = 0.0 

    """
        
    def __init__(self):
        """ Initialization """
        
        # Initialize BaseComponent first, then sphere
        BaseComponent.__init__(self)
        CSimCylinderF.__init__(self)
        
        ## Name of the model
        self.name = "SimCylinderF"
   
    def clone(self):
        """ Return a identical copy of self """
        obj = SimCylinderF()
        obj.params = copy.deepcopy(self.params)
        return obj   
   
    def run(self, x = 0.0):
        """ Evaluate the model
            @param x: input q, or [q,phi]
            @return: scattering function P(q)
        """
        
        return CSimCylinderF.run(self, x)
   
# End of file
