# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataExplorerUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataLoadWidget(object):
    def setupUi(self, DataLoadWidget):
        DataLoadWidget.setObjectName(_fromUtf8("DataLoadWidget"))
        DataLoadWidget.resize(517, 693)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataLoadWidget.sizePolicy().hasHeightForWidth())
        DataLoadWidget.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/ball.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataLoadWidget.setWindowIcon(icon)
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dataTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.dataTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmdLoad = QtGui.QPushButton(self.groupBox)
        self.cmdLoad.setObjectName(_fromUtf8("cmdLoad"))
        self.horizontalLayout_2.addWidget(self.cmdLoad)
        self.cbSelect = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSelect.sizePolicy().hasHeightForWidth())
        self.cbSelect.setSizePolicy(sizePolicy)
        self.cbSelect.setObjectName(_fromUtf8("cbSelect"))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cbSelect)
        spacerItem = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cmdDeleteData = QtGui.QPushButton(self.groupBox)
        self.cmdDeleteData.setObjectName(_fromUtf8("cmdDeleteData"))
        self.horizontalLayout_2.addWidget(self.cmdDeleteData)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.treeView = QtGui.QTreeView(self.groupBox)
        self.treeView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.treeView.setAcceptDrops(True)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.treeView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.treeView.header().setVisible(False)
        self.gridLayout.addWidget(self.treeView, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdFreeze = QtGui.QPushButton(self.groupBox)
        self.cmdFreeze.setObjectName(_fromUtf8("cmdFreeze"))
        self.horizontalLayout.addWidget(self.cmdFreeze)
        spacerItem1 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdSendTo = QtGui.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/file_send-128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmdSendTo.setIcon(icon1)
        self.cmdSendTo.setIconSize(QtCore.QSize(32, 32))
        self.cmdSendTo.setObjectName(_fromUtf8("cmdSendTo"))
        self.horizontalLayout.addWidget(self.cmdSendTo)
        self.cbFitting = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFitting.sizePolicy().hasHeightForWidth())
        self.cbFitting.setSizePolicy(sizePolicy)
        self.cbFitting.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbFitting.setObjectName(_fromUtf8("cbFitting"))
        self.cbFitting.addItem(_fromUtf8(""))
        self.cbFitting.addItem(_fromUtf8(""))
        self.cbFitting.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbFitting)
        self.chkBatch = QtGui.QCheckBox(self.groupBox)
        self.chkBatch.setObjectName(_fromUtf8("chkBatch"))
        self.horizontalLayout.addWidget(self.chkBatch)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.dataTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmdNew = QtGui.QPushButton(self.groupBox_3)
        self.cmdNew.setObjectName(_fromUtf8("cmdNew"))
        self.gridLayout_3.addWidget(self.cmdNew, 0, 0, 1, 1)
        self.cmdAppend = QtGui.QPushButton(self.groupBox_3)
        self.cmdAppend.setObjectName(_fromUtf8("cmdAppend"))
        self.gridLayout_3.addWidget(self.cmdAppend, 1, 0, 1, 1)
        self.cbgraph = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbgraph.sizePolicy().hasHeightForWidth())
        self.cbgraph.setSizePolicy(sizePolicy)
        self.cbgraph.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbgraph.setObjectName(_fromUtf8("cbgraph"))
        self.gridLayout_3.addWidget(self.cbgraph, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(108, 111, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.cmdHelp = QtGui.QPushButton(self.dataTab)
        self.cmdHelp.setObjectName(_fromUtf8("cmdHelp"))
        self.gridLayout_2.addWidget(self.cmdHelp, 0, 2, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        DataLoadWidget.addTab(self.dataTab, _fromUtf8(""))
        self.theoryTab = QtGui.QWidget()
        self.theoryTab.setObjectName(_fromUtf8("theoryTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.theoryTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_2 = QtGui.QGroupBox(self.theoryTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(353, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cmdDeleteTheory = QtGui.QPushButton(self.groupBox_2)
        self.cmdDeleteTheory.setObjectName(_fromUtf8("cmdDeleteTheory"))
        self.horizontalLayout_3.addWidget(self.cmdDeleteTheory)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.freezeView = QtGui.QTreeView(self.groupBox_2)
        self.freezeView.setObjectName(_fromUtf8("freezeView"))
        self.freezeView.header().setVisible(False)
        self.gridLayout_4.addWidget(self.freezeView, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.theoryTab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cmdNew_2 = QtGui.QPushButton(self.groupBox_4)
        self.cmdNew_2.setObjectName(_fromUtf8("cmdNew_2"))
        self.gridLayout_7.addWidget(self.cmdNew_2, 0, 0, 1, 1)
        self.cmdAppend_2 = QtGui.QPushButton(self.groupBox_4)
        self.cmdAppend_2.setObjectName(_fromUtf8("cmdAppend_2"))
        self.gridLayout_7.addWidget(self.cmdAppend_2, 1, 0, 1, 1)
        self.cbgraph_2 = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbgraph_2.sizePolicy().hasHeightForWidth())
        self.cbgraph_2.setSizePolicy(sizePolicy)
        self.cbgraph_2.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbgraph_2.setObjectName(_fromUtf8("cbgraph_2"))
        self.cbgraph_2.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cbgraph_2, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(108, 111, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.cmdHelp_2 = QtGui.QPushButton(self.theoryTab)
        self.cmdHelp_2.setObjectName(_fromUtf8("cmdHelp_2"))
        self.gridLayout_5.addWidget(self.cmdHelp_2, 0, 2, 1, 1, QtCore.Qt.AlignBottom)
        self.gridLayout_8.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        DataLoadWidget.addTab(self.theoryTab, _fromUtf8(""))
        self.actionDataInfo = QtGui.QAction(DataLoadWidget)
        self.actionDataInfo.setObjectName(_fromUtf8("actionDataInfo"))
        self.actionSaveAs = QtGui.QAction(DataLoadWidget)
        self.actionSaveAs.setObjectName(_fromUtf8("actionSaveAs"))
        self.actionQuickPlot = QtGui.QAction(DataLoadWidget)
        self.actionQuickPlot.setObjectName(_fromUtf8("actionQuickPlot"))
        self.actionQuick3DPlot = QtGui.QAction(DataLoadWidget)
        self.actionQuick3DPlot.setObjectName(_fromUtf8("actionQuick3DPlot"))
        self.actionEditMask = QtGui.QAction(DataLoadWidget)
        self.actionEditMask.setObjectName(_fromUtf8("actionEditMask"))

        self.retranslateUi(DataLoadWidget)
        DataLoadWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataLoadWidget)

    def retranslateUi(self, DataLoadWidget):
        DataLoadWidget.setWindowTitle(_translate("DataLoadWidget", "TabWidget", None))
        self.groupBox.setTitle(_translate("DataLoadWidget", "Data", None))
        self.cmdLoad.setText(_translate("DataLoadWidget", "Load", None))
        self.cbSelect.setItemText(0, _translate("DataLoadWidget", "Select all", None))
        self.cbSelect.setItemText(1, _translate("DataLoadWidget", "Unselect all", None))
        self.cbSelect.setItemText(2, _translate("DataLoadWidget", "Select all 1D", None))
        self.cbSelect.setItemText(3, _translate("DataLoadWidget", "Unselect all 1D", None))
        self.cbSelect.setItemText(4, _translate("DataLoadWidget", "Select all 2D", None))
        self.cbSelect.setItemText(5, _translate("DataLoadWidget", "Unselect all 2D", None))
        self.cmdDeleteData.setText(_translate("DataLoadWidget", "Delete", None))
        self.cmdFreeze.setText(_translate("DataLoadWidget", "Freeze Theory", None))
        self.cmdSendTo.setText(_translate("DataLoadWidget", "...", None))
        self.cbFitting.setItemText(0, _translate("DataLoadWidget", "Fitting", None))
        self.cbFitting.setItemText(1, _translate("DataLoadWidget", "Pr inversion", None))
        self.cbFitting.setItemText(2, _translate("DataLoadWidget", "Invariant", None))
        self.chkBatch.setText(_translate("DataLoadWidget", "Batch mode", None))
        self.groupBox_3.setTitle(_translate("DataLoadWidget", "Plot", None))
        self.cmdNew.setText(_translate("DataLoadWidget", "Create New", None))
        self.cmdAppend.setText(_translate("DataLoadWidget", "Append to", None))
        self.cmdHelp.setText(_translate("DataLoadWidget", "Help", None))
        DataLoadWidget.setTabText(DataLoadWidget.indexOf(self.dataTab), _translate("DataLoadWidget", "Data", None))
        self.groupBox_2.setTitle(_translate("DataLoadWidget", "Theory", None))
        self.cmdDeleteTheory.setText(_translate("DataLoadWidget", "Delete", None))
        self.groupBox_4.setTitle(_translate("DataLoadWidget", "Plot", None))
        self.cmdNew_2.setText(_translate("DataLoadWidget", "Create New", None))
        self.cmdAppend_2.setText(_translate("DataLoadWidget", "Append to", None))
        self.cbgraph_2.setItemText(0, _translate("DataLoadWidget", "Graph1", None))
        self.cmdHelp_2.setText(_translate("DataLoadWidget", "Help", None))
        DataLoadWidget.setTabText(DataLoadWidget.indexOf(self.theoryTab), _translate("DataLoadWidget", "Theory", None))
        self.actionDataInfo.setText(_translate("DataLoadWidget", "Data Info", None))
        self.actionSaveAs.setText(_translate("DataLoadWidget", "Save As", None))
        self.actionQuickPlot.setText(_translate("DataLoadWidget", "Quick Plot", None))
        self.actionQuick3DPlot.setText(_translate("DataLoadWidget", "Quick 3DPlot (slow)", None))
        self.actionEditMask.setText(_translate("DataLoadWidget", "Edit Mask", None))

import main_resources_rc

class DataLoadWidget(QtGui.QTabWidget, Ui_DataLoadWidget):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QTabWidget.__init__(self, parent)

        self.setupUi(self)

