# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(915, 555)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/ball.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuCopy_Params_As = QtGui.QMenu(self.menuEdit)
        self.menuCopy_Params_As.setObjectName(_fromUtf8("menuCopy_Params_As"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTool = QtGui.QMenu(self.menubar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        self.menuFitting = QtGui.QMenu(self.menubar)
        self.menuFitting.setObjectName(_fromUtf8("menuFitting"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionReset = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset.setIcon(icon1)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionReport = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/report.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon3)
        self.actionReport.setObjectName(_fromUtf8("actionReport"))
        self.actionUndo = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("res/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionUndo.setIcon(icon4)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon5)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCopy = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon6)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon7)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionBookmarks = QtGui.QAction(MainWindow)
        self.actionBookmarks.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/bookmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBookmarks.setIcon(icon8)
        self.actionBookmarks.setObjectName(_fromUtf8("actionBookmarks"))
        self.actionPerspective = QtGui.QAction(MainWindow)
        self.actionPerspective.setObjectName(_fromUtf8("actionPerspective"))
        self.actionLoadData = QtGui.QAction(MainWindow)
        self.actionLoadData.setObjectName(_fromUtf8("actionLoadData"))
        self.actionLoad_Data_Folder = QtGui.QAction(MainWindow)
        self.actionLoad_Data_Folder.setObjectName(_fromUtf8("actionLoad_Data_Folder"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionOpen_Analysis = QtGui.QAction(MainWindow)
        self.actionOpen_Analysis.setObjectName(_fromUtf8("actionOpen_Analysis"))
        self.actionSave_Analysis = QtGui.QAction(MainWindow)
        self.actionSave_Analysis.setObjectName(_fromUtf8("actionSave_Analysis"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShow_Grid_Window = QtGui.QAction(MainWindow)
        self.actionShow_Grid_Window.setObjectName(_fromUtf8("actionShow_Grid_Window"))
        self.actionHide_Toolbar = QtGui.QAction(MainWindow)
        self.actionHide_Toolbar.setObjectName(_fromUtf8("actionHide_Toolbar"))
        self.actionStartup_Settings = QtGui.QAction(MainWindow)
        self.actionStartup_Settings.setObjectName(_fromUtf8("actionStartup_Settings"))
        self.actionCategry_Manager = QtGui.QAction(MainWindow)
        self.actionCategry_Manager.setObjectName(_fromUtf8("actionCategry_Manager"))
        self.actionData_Operation = QtGui.QAction(MainWindow)
        self.actionData_Operation.setObjectName(_fromUtf8("actionData_Operation"))
        self.actionSLD_Calculator = QtGui.QAction(MainWindow)
        self.actionSLD_Calculator.setObjectName(_fromUtf8("actionSLD_Calculator"))
        self.actionDensity_Volume_Calculator = QtGui.QAction(MainWindow)
        self.actionDensity_Volume_Calculator.setObjectName(_fromUtf8("actionDensity_Volume_Calculator"))
        self.actionSlit_Size_Calculator = QtGui.QAction(MainWindow)
        self.actionSlit_Size_Calculator.setObjectName(_fromUtf8("actionSlit_Size_Calculator"))
        self.actionSAS_Resolution_Estimator = QtGui.QAction(MainWindow)
        self.actionSAS_Resolution_Estimator.setObjectName(_fromUtf8("actionSAS_Resolution_Estimator"))
        self.actionGeneric_Scattering_Calculator = QtGui.QAction(MainWindow)
        self.actionGeneric_Scattering_Calculator.setObjectName(_fromUtf8("actionGeneric_Scattering_Calculator"))
        self.actionPython_Shell_Editor = QtGui.QAction(MainWindow)
        self.actionPython_Shell_Editor.setObjectName(_fromUtf8("actionPython_Shell_Editor"))
        self.actionImage_Viewer = QtGui.QAction(MainWindow)
        self.actionImage_Viewer.setObjectName(_fromUtf8("actionImage_Viewer"))
        self.actionNew_Fit_Page = QtGui.QAction(MainWindow)
        self.actionNew_Fit_Page.setObjectName(_fromUtf8("actionNew_Fit_Page"))
        self.actionConstrained_Fit = QtGui.QAction(MainWindow)
        self.actionConstrained_Fit.setObjectName(_fromUtf8("actionConstrained_Fit"))
        self.actionCombine_Batch_Fit = QtGui.QAction(MainWindow)
        self.actionCombine_Batch_Fit.setObjectName(_fromUtf8("actionCombine_Batch_Fit"))
        self.actionFit_Options = QtGui.QAction(MainWindow)
        self.actionFit_Options.setObjectName(_fromUtf8("actionFit_Options"))
        self.actionFit_Results = QtGui.QAction(MainWindow)
        self.actionFit_Results.setObjectName(_fromUtf8("actionFit_Results"))
        self.actionChain_Fitting = QtGui.QAction(MainWindow)
        self.actionChain_Fitting.setObjectName(_fromUtf8("actionChain_Fitting"))
        self.actionEdit_Custom_Model = QtGui.QAction(MainWindow)
        self.actionEdit_Custom_Model.setObjectName(_fromUtf8("actionEdit_Custom_Model"))
        self.actionCascade = QtGui.QAction(MainWindow)
        self.actionCascade.setObjectName(_fromUtf8("actionCascade"))
        self.actionTile_Horizontally = QtGui.QAction(MainWindow)
        self.actionTile_Horizontally.setObjectName(_fromUtf8("actionTile_Horizontally"))
        self.actionTile_Vertically = QtGui.QAction(MainWindow)
        self.actionTile_Vertically.setObjectName(_fromUtf8("actionTile_Vertically"))
        self.actionArrange_Icons = QtGui.QAction(MainWindow)
        self.actionArrange_Icons.setObjectName(_fromUtf8("actionArrange_Icons"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setObjectName(_fromUtf8("actionPrevious"))
        self.actionFitting = QtGui.QAction(MainWindow)
        self.actionFitting.setCheckable(True)
        self.actionFitting.setObjectName(_fromUtf8("actionFitting"))
        self.actionInversion = QtGui.QAction(MainWindow)
        self.actionInversion.setCheckable(True)
        self.actionInversion.setObjectName(_fromUtf8("actionInversion"))
        self.actionInvariant = QtGui.QAction(MainWindow)
        self.actionInvariant.setCheckable(True)
        self.actionInvariant.setObjectName(_fromUtf8("actionInvariant"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.actionAcknowledge = QtGui.QAction(MainWindow)
        self.actionAcknowledge.setObjectName(_fromUtf8("actionAcknowledge"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCheck_for_update = QtGui.QAction(MainWindow)
        self.actionCheck_for_update.setObjectName(_fromUtf8("actionCheck_for_update"))
        self.actionExcel = QtGui.QAction(MainWindow)
        self.actionExcel.setObjectName(_fromUtf8("actionExcel"))
        self.actionLatex = QtGui.QAction(MainWindow)
        self.actionLatex.setObjectName(_fromUtf8("actionLatex"))
        self.menu_File.addAction(self.actionLoadData)
        self.menu_File.addAction(self.actionLoad_Data_Folder)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen_Project)
        self.menu_File.addAction(self.actionOpen_Analysis)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_Analysis)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menuCopy_Params_As.addAction(self.actionExcel)
        self.menuCopy_Params_As.addAction(self.actionLatex)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuCopy_Params_As.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReport)
        self.menuEdit.addAction(self.actionReset)
        self.menuView.addAction(self.actionShow_Grid_Window)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionHide_Toolbar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStartup_Settings)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCategry_Manager)
        self.menuTool.addAction(self.actionData_Operation)
        self.menuTool.addAction(self.actionSLD_Calculator)
        self.menuTool.addAction(self.actionDensity_Volume_Calculator)
        self.menuTool.addAction(self.actionSlit_Size_Calculator)
        self.menuTool.addAction(self.actionSAS_Resolution_Estimator)
        self.menuTool.addAction(self.actionGeneric_Scattering_Calculator)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionPython_Shell_Editor)
        self.menuTool.addAction(self.actionImage_Viewer)
        self.menuFitting.addAction(self.actionNew_Fit_Page)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionConstrained_Fit)
        self.menuFitting.addAction(self.actionCombine_Batch_Fit)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionFit_Options)
        self.menuFitting.addAction(self.actionFit_Results)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionChain_Fitting)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionEdit_Custom_Model)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionTile_Horizontally)
        self.menuWindow.addAction(self.actionTile_Vertically)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionArrange_Icons)
        self.menuWindow.addAction(self.actionNext)
        self.menuWindow.addAction(self.actionPrevious)
        self.menuWindow.addSeparator()
        self.menuAnalysis.addAction(self.actionFitting)
        self.menuAnalysis.addAction(self.actionInversion)
        self.menuAnalysis.addAction(self.actionInvariant)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAcknowledge)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuFitting.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionReport)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionBookmarks)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuCopy_Params_As.setTitle(_translate("MainWindow", "Copy Params To Format...", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuTool.setTitle(_translate("MainWindow", "Tool", None))
        self.menuFitting.setTitle(_translate("MainWindow", "Fitting", None))
        self.menuWindow.setTitle(_translate("MainWindow", "Window", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionReset.setText(_translate("MainWindow", "Reset Page", None))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset", None))
        self.actionSave.setText(_translate("MainWindow", "Save Project", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save", None))
        self.actionReport.setText(_translate("MainWindow", "Report Results", None))
        self.actionReport.setToolTip(_translate("MainWindow", "report", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionRedo.setText(_translate("MainWindow", "Redo", None))
        self.actionRedo.setToolTip(_translate("MainWindow", "Redo", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy Params", None))
        self.actionCopy.setToolTip(_translate("MainWindow", "Copy parameter values", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste Params", None))
        self.actionPaste.setToolTip(_translate("MainWindow", "Paste parameter values", None))
        self.actionBookmarks.setText(_translate("MainWindow", "Bookmarks", None))
        self.actionPerspective.setText(_translate("MainWindow", "Perspective", None))
        self.actionLoadData.setText(_translate("MainWindow", "Load Data File(s)", None))
        self.actionLoad_Data_Folder.setText(_translate("MainWindow", "Load Data Folder", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project", None))
        self.actionOpen_Analysis.setText(_translate("MainWindow", "Open Analysis", None))
        self.actionSave_Analysis.setText(_translate("MainWindow", "Save Analysis", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionShow_Grid_Window.setText(_translate("MainWindow", "Show Grid Window", None))
        self.actionHide_Toolbar.setText(_translate("MainWindow", "Hide Toolbar", None))
        self.actionStartup_Settings.setText(_translate("MainWindow", "Startup Settings", None))
        self.actionCategry_Manager.setText(_translate("MainWindow", "Categry Manager", None))
        self.actionData_Operation.setText(_translate("MainWindow", "Data Operation", None))
        self.actionSLD_Calculator.setText(_translate("MainWindow", "SLD Calculator", None))
        self.actionDensity_Volume_Calculator.setText(_translate("MainWindow", "Density/Volume Calculator", None))
        self.actionSlit_Size_Calculator.setText(_translate("MainWindow", "Slit Size Calculator", None))
        self.actionSAS_Resolution_Estimator.setText(_translate("MainWindow", "SAS Resolution Estimator", None))
        self.actionGeneric_Scattering_Calculator.setText(_translate("MainWindow", "Generic Scattering Calculator", None))
        self.actionPython_Shell_Editor.setText(_translate("MainWindow", "Python Shell/Editor", None))
        self.actionImage_Viewer.setText(_translate("MainWindow", "Image Viewer", None))
        self.actionNew_Fit_Page.setText(_translate("MainWindow", "New Fit Page", None))
        self.actionConstrained_Fit.setText(_translate("MainWindow", "Constrained or Simultaneous Fit", None))
        self.actionCombine_Batch_Fit.setText(_translate("MainWindow", "Combine Batch Fit", None))
        self.actionFit_Options.setText(_translate("MainWindow", "Fit Options", None))
        self.actionFit_Results.setText(_translate("MainWindow", "Fit Results", None))
        self.actionChain_Fitting.setText(_translate("MainWindow", "Chain Fitting (BatchFit only)", None))
        self.actionEdit_Custom_Model.setText(_translate("MainWindow", "Edit Custom Model", None))
        self.actionCascade.setText(_translate("MainWindow", "Cascade", None))
        self.actionTile_Horizontally.setText(_translate("MainWindow", "Tile Horizontally", None))
        self.actionTile_Vertically.setText(_translate("MainWindow", "Tile Vertically", None))
        self.actionArrange_Icons.setText(_translate("MainWindow", "Arrange Icons", None))
        self.actionNext.setText(_translate("MainWindow", "Next", None))
        self.actionPrevious.setText(_translate("MainWindow", "Previous", None))
        self.actionFitting.setText(_translate("MainWindow", "Fitting", None))
        self.actionInversion.setText(_translate("MainWindow", "Pr Inversion", None))
        self.actionInvariant.setText(_translate("MainWindow", "Invariant", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial", None))
        self.actionAcknowledge.setText(_translate("MainWindow", "Acknowledge", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionCheck_for_update.setText(_translate("MainWindow", "Check for update", None))
        self.actionExcel.setText(_translate("MainWindow", "Excel", None))
        self.actionLatex.setText(_translate("MainWindow", "Latex", None))

import main_resources_rc

class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

