# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TabbedFileLoadUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataLoadWidget(object):
    def setupUi(self, DataLoadWidget):
        DataLoadWidget.setObjectName(_fromUtf8("DataLoadWidget"))
        DataLoadWidget.resize(481, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/res/ball.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DataLoadWidget.setWindowIcon(icon)
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dataTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label = QtGui.QLabel(self.dataTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.cbSelect = QtGui.QComboBox(self.dataTab)
        self.cbSelect.setObjectName(_fromUtf8("cbSelect"))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.cbSelect.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbSelect, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(352, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.dataTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeView = QtGui.QTreeView(self.groupBox)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.treeView.header().setVisible(False)
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 3)
        self.cmdLoad = QtGui.QPushButton(self.groupBox)
        self.cmdLoad.setObjectName(_fromUtf8("cmdLoad"))
        self.gridLayout.addWidget(self.cmdLoad, 1, 0, 1, 1)
        self.cmdDelete = QtGui.QPushButton(self.groupBox)
        self.cmdDelete.setObjectName(_fromUtf8("cmdDelete"))
        self.gridLayout.addWidget(self.cmdDelete, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdSendTo = QtGui.QPushButton(self.groupBox)
        self.cmdSendTo.setObjectName(_fromUtf8("cmdSendTo"))
        self.horizontalLayout.addWidget(self.cmdSendTo)
        self.cbFitting = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFitting.sizePolicy().hasHeightForWidth())
        self.cbFitting.setSizePolicy(sizePolicy)
        self.cbFitting.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbFitting.setObjectName(_fromUtf8("cbFitting"))
        self.cbFitting.addItem(_fromUtf8(""))
        self.cbFitting.addItem(_fromUtf8(""))
        self.cbFitting.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbFitting)
        self.chkBatch = QtGui.QCheckBox(self.groupBox)
        self.chkBatch.setObjectName(_fromUtf8("chkBatch"))
        self.horizontalLayout.addWidget(self.chkBatch)
        spacerItem2 = QtGui.QSpacerItem(197, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 2, 0, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(self.dataTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmdNew = QtGui.QPushButton(self.groupBox_3)
        self.cmdNew.setObjectName(_fromUtf8("cmdNew"))
        self.gridLayout_3.addWidget(self.cmdNew, 0, 0, 1, 1)
        self.cmdAppend = QtGui.QPushButton(self.groupBox_3)
        self.cmdAppend.setObjectName(_fromUtf8("cmdAppend"))
        self.gridLayout_3.addWidget(self.cmdAppend, 1, 0, 1, 1)
        self.cbgraph = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbgraph.sizePolicy().hasHeightForWidth())
        self.cbgraph.setSizePolicy(sizePolicy)
        self.cbgraph.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cbgraph.setObjectName(_fromUtf8("cbgraph"))
        self.cbgraph.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbgraph, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 3, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(287, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 2, 1, 1)
        DataLoadWidget.addTab(self.dataTab, _fromUtf8(""))
        self.theoryTab = QtGui.QWidget()
        self.theoryTab.setObjectName(_fromUtf8("theoryTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.theoryTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.theoryTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listView = QtGui.QListView(self.groupBox_2)
        self.listView.setDragEnabled(True)
        self.listView.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listView.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_4.addWidget(self.listView, 0, 0, 1, 2)
        self.cmdFreeze = QtGui.QPushButton(self.groupBox_2)
        self.cmdFreeze.setObjectName(_fromUtf8("cmdFreeze"))
        self.gridLayout_4.addWidget(self.cmdFreeze, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(353, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        DataLoadWidget.addTab(self.theoryTab, _fromUtf8(""))

        self.retranslateUi(DataLoadWidget)
        DataLoadWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataLoadWidget)

    def retranslateUi(self, DataLoadWidget):
        DataLoadWidget.setWindowTitle(_translate("DataLoadWidget", "TabWidget", None))
        self.label.setText(_translate("DataLoadWidget", "Selection Options", None))
        self.cbSelect.setItemText(0, _translate("DataLoadWidget", "Select all", None))
        self.cbSelect.setItemText(1, _translate("DataLoadWidget", "Unselect all", None))
        self.cbSelect.setItemText(2, _translate("DataLoadWidget", "Select all 1D", None))
        self.cbSelect.setItemText(3, _translate("DataLoadWidget", "Unselect all 1D", None))
        self.cbSelect.setItemText(4, _translate("DataLoadWidget", "Select all 2D", None))
        self.cbSelect.setItemText(5, _translate("DataLoadWidget", "Unselect all 2D", None))
        self.groupBox.setTitle(_translate("DataLoadWidget", "Data", None))
        self.cmdLoad.setText(_translate("DataLoadWidget", "Load", None))
        self.cmdDelete.setText(_translate("DataLoadWidget", "Delete", None))
        self.cmdSendTo.setText(_translate("DataLoadWidget", "Send to", None))
        self.cbFitting.setItemText(0, _translate("DataLoadWidget", "Fitting", None))
        self.cbFitting.setItemText(1, _translate("DataLoadWidget", "Pr inversion", None))
        self.cbFitting.setItemText(2, _translate("DataLoadWidget", "Invariant", None))
        self.chkBatch.setText(_translate("DataLoadWidget", "Batch mode", None))
        self.groupBox_3.setTitle(_translate("DataLoadWidget", "Plot", None))
        self.cmdNew.setText(_translate("DataLoadWidget", "New", None))
        self.cmdAppend.setText(_translate("DataLoadWidget", "Append to", None))
        self.cbgraph.setItemText(0, _translate("DataLoadWidget", "Graph1", None))
        DataLoadWidget.setTabText(DataLoadWidget.indexOf(self.dataTab), _translate("DataLoadWidget", "Data", None))
        self.groupBox_2.setTitle(_translate("DataLoadWidget", "Theory", None))
        self.cmdFreeze.setText(_translate("DataLoadWidget", "Freeze", None))
        DataLoadWidget.setTabText(DataLoadWidget.indexOf(self.theoryTab), _translate("DataLoadWidget", "Theory", None))

import main_resources_rc

class DataLoadWidget(QtGui.QTabWidget, Ui_DataLoadWidget):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QTabWidget.__init__(self, parent)

        self.setupUi(self)

