# Generated by Django 4.2.2 on 2023-07-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0003_fit_qmaximum_fit_qminimum_fit_magnetism_fit_model_and_more'),
        ('analyze', '0003_remove_analysisbase_model_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisparameterbase',
            name='model_id',
        ),
        migrations.AddField(
            model_name='analysisparameterbase',
            name='base_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analyze.analysisbase'),
        ),
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='lower_limit',
            field=models.FloatField(blank=True, default=None, help_text='optional lower limit', null=True),
        ),
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='upper_limit',
            field=models.FloatField(blank=True, default=None, help_text='optional upper limit', null=True),
        ),
        migrations.AlterField(
            model_name='analysisparameterbase',
            name='value',
            field=models.FloatField(default=None, help_text='the value of the parameter'),
        ),
        migrations.DeleteModel(
            name='AnalysisModelBase',
        ),
    ]
