/**
 * DANSE function header
 * 
 * WARNING: THIS FILE WAS GENERATED BY HEADERGENERATOR.PY
 *          DO NOT MODIFY THIS FILE
 *
 *  This code was written as part of the DANSE project
 *  http://danse.us/trac/sans/
 *  
 *  @copyright 2007: University of Tennessee, for the DANSE project
 *
 */
#if !defined(function_header_h)
#define function_header_h

[FUNCTION_LIST]
#endif

