#!/usr/bin/env python
"""
Script to collect sphinx sources for building.

SasView docs are in multiple places:

- the in-doc-tree parts of the documentation that SasView provides,
  found under "docs".
- the in-source-tree parts of the documentation that SasView provides,
  found within "src/sas"
- Documentation that comes from sibling modules such as sasdata and sasmodels

These sources must be collected, manipulated, and assembled before being
given to sphinx.

The collected resources are assembled in two phases:

1. Everything is gathered into a temporary staging tree (under TMP_DIR,
   which also holds the intermediate resources collected by
   ``src/sas/system/resources.py``).
2. The staged tree is then synchronised into the live sphinx source tree
   (SPHINX_SOURCE / ``source-temp``) using content hashing.  Only files
   that are new or that changed are copied, so unchanged files keep their
   modification time and sphinx can re-use its cache.  Files that are no
   longer produced (stale) are removed.  Timestamps in the source
   directories cannot be trusted, so file contents are compared using a
   simple (non-cryptographic) hash.
"""

import argparse
import hashlib
import os
import shutil
from pathlib import Path

# sphinx paths for the document
BASE = Path(__file__).parent
SPHINX_BUILD = BASE / "build"
SPHINX_SOURCE = BASE / "source-temp"

# Temporary working tree. `resources.py` fills TMP_DIR with the sasmodels
# and sasdata docs sources; the assembled result is staged in a sub-directory
# here before being deployed into SPHINX_SOURCE.
TMP_DIR = BASE / "tmp"
STAGING = TMP_DIR / "sphinx-source"

# Paths inside SPHINX_SOURCE that are not managed by this script because
# they are generated by later build steps (e.g. sphinx.ext.apidoc).  Files
# under these prefixes are never pruned when missing from the staging tree.
UNMANAGED = ("dev/sasview-api",)

# user ui docs
PERSPECTIVES_TARGET = STAGING / "user" / "qtgui" / "Perspectives"

# sasview paths
SASVIEW_SRC = (BASE.parent.parent / "src").resolve()
SASVIEW_DOCS = BASE / "source"
SASVIEW_MEDIA_SOURCE = SASVIEW_SRC / "sas"

# sasmodels paths
SASMODELS_DOCS = TMP_DIR / "sasmodels" / "docs"
SASMODELS_MODEL_SOURCE = SASMODELS_DOCS / "model"
SASMODELS_MODEL_TARGET = STAGING / "user" / "models"
SASMODELS_API_SOURCE = SASMODELS_DOCS / "api"
SASMODELS_API_TARGET = STAGING / "dev" / "sasmodels-api"
SASMODELS_DEV_SOURCE = SASMODELS_DOCS / "developer"
SASMODELS_DEV_TARGET = STAGING / "dev" / "sasmodels-dev"
SASMODELS_GUIDE_SOURCE = SASMODELS_DOCS / "guide"
SASMODELS_GUIDE_TARGET = PERSPECTIVES_TARGET / "Fitting"
SASMODELS_GUIDE_EXCLUDE = [
    "index.rst",
    "install.rst",
    "intro.rst",
]

# sasdata paths
SASDATA_DOCS = TMP_DIR / "sasdata" / "docs"
SASDATA_DEV_SOURCE = SASDATA_DOCS / "dev"
SASDATA_DEV_TARGET = STAGING / "dev" / "sasdata-dev"
SASDATA_GUIDE_SOURCE = SASDATA_DOCS / "user"
SASDATA_GUIDE_TARGET = STAGING / "user" / "data"


def inplace_change(filename, old_string, new_string):
    with open(filename, encoding="UTF-8") as f:
        s = f.read()

    if old_string in s:
        print(f'Changing "{old_string}" to "{new_string}" in {filename}')

        s = s.replace(old_string, new_string)
        with open(filename, "w", encoding="UTF-8") as f:
            f.write(s)

    else:
        print(f'No occurrences of "{old_string}" found in {filename}.')


def _remove_dir(dir_path):
    """Removes the given directory."""
    if dir_path.is_dir():
        print(f'Removing "{dir_path}"... ')
        shutil.rmtree(dir_path)


def clean():
    """Clean the whole build

    The staging tree, live sphinx source tree and build outputs. Are all
    deleted. Use this to force a completely clean rebuild without any
    intermediate caching of source files by this script or build artifacts
    by sphinx.
    """
    print("=== Cleaning Sphinx Build ===")
    _remove_dir(SPHINX_BUILD)
    _remove_dir(SPHINX_SOURCE)
    _remove_dir(STAGING)


def copy_sasview_docs():
    """Copy the SasView base source and toctrees

    Copies the in-doc-tree parts of the documentation that SasView provides,
    found under "docs", into the staging area ready for other items to be
    added to them to make the completed source.
    """
    print("=== Copying Source toctrees ===")
    shutil.copytree(SASVIEW_DOCS, STAGING)


def retrieve_user_docs():
    """Copy the SasView documentation from the source code tree

    Copies the documentation of any media/ directories in src/, and puts them
    in an appropriately named directory of the staging tree. For example:

        sas/../[MODULE]/media/dir/A.rst
        sas/../[MODULE]/media/B.rst

    gets copied to a new location:

        docs/sphinx-docs/tmp/sphinx-source/user/[MODULE]/dir/A.rst
        docs/sphinx-docs/tmp/sphinx-source/user/[MODULE]/B.rst

    so that Sphinx may pick it up when generating the documentation.
    """
    print("=== Retrieve User Docs ===")

    # Copy documentation files from sas/.../media to the sphinx directory
    for root, dirs, _ in os.walk(SASVIEW_MEDIA_SOURCE):
        # CRUFT: from 3.12, use SASVIEW_MEDIA_SOURCE.walk()
        if "media" in dirs:
            source_dir = (Path(root) / "media").resolve()
            relative = source_dir.relative_to(SASVIEW_MEDIA_SOURCE).parent
            dest_dir = STAGING / "user" / relative

            print(f'Found sasview docs folder at "{relative}".')
            shutil.copytree(source_dir, dest_dir, dirs_exist_ok=True)

    print("=== Sasmodels Docs ===")
    shutil.copy(SASMODELS_DOCS / "rst_prolog", STAGING)
    shutil.copytree(SASMODELS_MODEL_SOURCE, SASMODELS_MODEL_TARGET, dirs_exist_ok=True)
    shutil.copytree(SASMODELS_API_SOURCE, SASMODELS_API_TARGET, dirs_exist_ok=True)
    shutil.copytree(SASMODELS_DEV_SOURCE, SASMODELS_DEV_TARGET, dirs_exist_ok=True)
    shutil.copytree(SASMODELS_GUIDE_SOURCE, SASMODELS_GUIDE_TARGET, dirs_exist_ok=True)
    for filename in SASMODELS_GUIDE_EXCLUDE:
        (SASMODELS_GUIDE_TARGET / filename).unlink()

    # Model category files reference the model as ../../model/name.rst.  Since
    # we are rearranging the tree, we need to update each of these links.
    catdir = SASMODELS_GUIDE_TARGET / "models"
    for filename in catdir.iterdir():
        inplace_change(catdir / filename, "../../model/", "/user/models/")


def retrieve_sasdata_docs():
    """Copy documentation from the SasData tree

    Copies select files from the ssdata documentation"""
    print("=== Sasdata Docs ===")
    shutil.copytree(SASDATA_DEV_SOURCE, SASDATA_DEV_TARGET, dirs_exist_ok=True)
    shutil.copytree(SASDATA_GUIDE_SOURCE, SASDATA_GUIDE_TARGET, dirs_exist_ok=True)


def _is_unmanaged(rel):
    """Whether the given relative path is owned by a later build step."""
    rel = rel.as_posix()
    return any(rel == u or rel.startswith(u + "/") for u in UNMANAGED)


def _file_hash(path, blocksize=65536):
    """Return a content hash for the file.

    SHA-256 (implemented in C in CPython's ``hashlib``) is used for change
    detection.  It is fast and correctly detects when a file differs; its
    cryptographic strength is irrelevant here.
    """
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(blocksize), b""):
            digest.update(block)
    return digest.digest()


def _same_content(src, dest):
    """Whether src and dest hold identical content

    Compare first the file size and then use a fast hash to compare the
    contents."""
    if src.stat().st_size != dest.stat().st_size:
        return False
    return _file_hash(src) == _file_hash(dest)


def sync_to_source():
    """Sync assembled staging tree into sphinx-source

    The assembled staging tree is deployed to the sphinx-source tree that
    will then be given to sphinx to compile. The sync is done to avoid
    touching files whose content is unchanged ensuring that modification
    times on files only change if the files have changed, allowing sphinx
    to aggressively cache.

    Notes:
    - Files are compared by content hash rather than modification time,
      which is not reliable in the source directories
      (`src/sas/system/resource.py -r` makes no attempt to manage timestamps)
    - Unchanged files are left in place (preserving their mtime so that
      sphinx can cache the work for them)
    - Updated files are copied
    - Stale files that are no longer produced in the staging tree are
      removed.
    """
    print("=== Syncing staging tree into sphinx source tree ===")
    source = STAGING
    dest = SPHINX_SOURCE
    dest.mkdir(parents=True, exist_ok=True)

    copied = 0
    unchanged = 0

    # Copy new / updated files, leaving identical ones (and their mtimes) alone.
    for src_file in source.rglob("*"):
        if not src_file.is_file():
            continue
        rel = src_file.relative_to(source)
        if _is_unmanaged(rel):
            continue
        dest_file = dest / rel
        if dest_file.is_file() and _same_content(src_file, dest_file):
            unchanged += 1
            continue
        dest_file.parent.mkdir(parents=True, exist_ok=True)
        action = "updating" if dest_file.exists() else "copying"
        print(f"  {action} {rel}")
        shutil.copy2(src_file, dest_file)
        copied += 1

    # Remove stale files: present in the sphinx tree but no longer produced.
    stale = [
        dest_file
        for dest_file in dest.rglob("*")
        if dest_file.is_file()
        and not _is_unmanaged(dest_file.relative_to(dest))
        and not (source / dest_file.relative_to(dest)).exists()
    ]
    for dest_file in stale:
        print(f"  removing stale {dest_file.relative_to(dest)}")
        dest_file.unlink()

    # Prune directories left empty by the removals (deepest first).
    for dir_path in sorted(
        (d for d in dest.rglob("*") if d.is_dir()),
        key=lambda p: len(p.parts),
        reverse=True,
    ):
        rel = dir_path.relative_to(dest)
        if _is_unmanaged(rel) or (source / rel).exists():
            continue
        try:
            dir_path.rmdir()  # only succeeds when empty
        except OSError:
            pass

    print(f"  {copied} file(s) copied, {unchanged} unchanged, {len(stale)} stale file(s) removed")


def collect(clean_first=False):
    """Assemble the collected sources and deploy them into the sphinx tree.

    With ``clean_first`` a completely clean rebuild is forced (staging tree,
    live sphinx source tree and build outputs are all removed first);
    otherwise only the staging tree is rebuilt and the live source tree is
    updated incrementally so that sphinx can cache its work.
    """
    if clean_first:
        clean()
    else:
        _remove_dir(STAGING)
    copy_sasview_docs()
    retrieve_user_docs()
    retrieve_sasdata_docs()
    sync_to_source()
    print("=== Done ===")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="remove the live sphinx source tree and build outputs first "
        "for a fully clean rebuild (default: incremental, preserving "
        "the sphinx cache)",
    )
    args = parser.parse_args()
    collect(clean_first=args.clean)
