# Generated by Django 4.2.2 on 2023-07-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitting", "0001_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fit",
            name="fit_model",
        ),
    ]
