# Generated by Django 4.2.2 on 2023-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitting", "0001_version"),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='Qmaximum',
            field=models.FloatField(blank=True, default=None, help_text='Maximum Q value for the fit', null=True),
        ),
        migrations.AddField(
            model_name='fit',
            name='Qminimum',
            field=models.FloatField(blank=True, default=None, help_text='Minimum Q value for the fit', null=True),
        ),
        migrations.AddField(
            model_name='fit',
            name='magnetism',
            field=models.BooleanField(default=False, help_text='Is magnetism being checked in this model?'),
        ),
        migrations.AddField(
            model_name='fit',
            name='model',
            field=models.CharField(blank=False, help_text='model string', max_length=256),
        ),
        migrations.AddField(
            model_name='fit',
            name='polydispersity',
            field=models.BooleanField(default=False, help_text='Is polydispersity being checked in this model'),
        ),
        migrations.DeleteModel(
            name='FitModel',
        ),
    ]
