# Generated by Django 4.2.2 on 2023-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0005_alter_fit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='optimizer',
            field=models.CharField(blank=True, help_text='optimizer string', max_length=50),
        ),
    ]
