name: Ruff

on: workflow_call

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix-only
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
          